### ISSUE TITLE
Implement a reverse geocoder to replace the "your coordinates" list

### ISSUE THREAD

**Issue by stevevance** [zorostang/chicago_bike_equity#31]
For implementing the access index, which is based on the user right-clicking a point on the map (and, in the future, searching for a specific address), we should tell the user the address for their point – instead of the coordinates. 

I know of one reliable reverse geocoder, and that's OpenStreetMap's [Nominatim service](http://wiki.openstreetmap.org/wiki/Nominatim#Reverse_Geocoding_.2F_Address_lookup). You might also find a Leaflet plugin that implements a reverse geocoder. I would start by looking at the [list of Leaflet plugins](http://leafletjs.com/plugins.html).

**Comment by guillermokrh** [comment]
Hey Steven,
All my changes have been committed.  Take a look at the new context menu options, "Show Address" and "Clear Comparison".  "Show Address" displays the address of the coordinates on the "Access Index" sidebar, and creates a blue popup on the map with the address.  I was thinking the pop-up might be good so that the person remembers where they clicked. Then I added a "Clear Comparison" function which will remove the addresses from the "Access Index" sidebar (however, this does not remove the pop-ups). 

Follow up questions:
1) How do you feel about the Clear Comparison function?  The context menu might not be the best place for it, but if we are going to compare access indices on the sidebar we'll need this somewhere.
2) How do you feel about the blue pop-up?  If you like it, should we figure out how to delete them as a part of the Clear Comparison function?
3)  Does the Show Coordinates option in the context menu have any other use?  Should I delete it?

Let me know!

**Comment by stevevance** [comment]
Thanks for doing this!
1. Put the "Clear" function in the sidebar. 
2. Find a new icon to represent the address. 
3. Nope, get rid of the "show coordinates" option.
