### ISSUE TITLE
Use Turf.js to develop a function that counts the number of grocery stores within 2 miles

### ISSUE THREAD

**Issue by stevevance** [zorostang/chicago_bike_equity#8]
Turf.js is a JavaScript library for Leaflet that does GIS functions and geospatial analysis within the user's browser. The implication is that we don't have to pre-process so many statistics. 

For example, in this issue, it would be useful to allow the user to right-click on the map and have the app tell the user how many grocery stores are within a certain distance.

**Comment by guillermokrh** [comment]
Hey Steven, I was wondering, what is your favorite web dev set-up?  I've used a combination of vim, the terminal, and Mozilla in the past, but I don't really feel it's ideal.  Let me know what combo of tools you use!

**Comment by stevevance** [comment]
I use Coda, Safari, and MAMP.

**Comment by guillermokrh** [comment]
So I've been playing around with turf.js and I've thought of a couple of ways to create a function that returns the closest grocery stores.  I also did some tests on some random geoJSON points I created, so here are my thoughts and concerns:

First Thought:
- use Distance to calculate distances between current point and ALL grocery stores, using a loop
- return stores that are within 2 miles
- CONCERN: this is may not be scalable, and could take long to calculate.  It depends on how much data we have.

Second Thought
- use Buffer to get a collection of Features that draws a polygon, enclosing the region within two miles
- use Counted to count the number of grocery stores in the polygon
- Return the count number, as well as the list of grocery stores
- CONCERN: Counted not working on FeatureCollection returned by Buffer

Third thought:
- use Buffer to get a collection of Features that draws a polygon
- use Merge to turn this collection of features into a Polygon type
- use Counted to count the number of grocery stores in the Polygon
- RESULT: Counted still not working, on Polygon returned by Merge

So far my results are based on test points that I've made, so they're not the geoJSON data of grocery stores, so just because this hasn't worked on my test points doesn't mean it won't work with the grocery store data.  I haven't been able to access the geoJSON data of grocery stores as variables, so I have questions as to how to get that (we can talk about it tonight). 

I think the success of turf.js will depend on whether the data we have fits into the parameter specifications of turf.js functions, because they seem to be very particular and not very flexible (ex: the turf.count function only takes a FeatureCollection of Polygon features as a parameter, and doesn't have equivalent functions for other types).

**Comment by stevevance** [comment]
1. I think you're right: this isn't scalable or fast on geographic features that have more than a few dozen points. Although I've done it before, just not with a JS library like Turf. 
2. I think this is the best approach out of the three. The Counted function doesn't seem so important because we can actually use other code to count the number of features in a returned GeoJSON object. 
3. FeatureCollection is probably a better level of GeoJSON to work within because it's a geography object that represents multiple shapes, whereas Polygon represents a single shape.

**Comment by guillermokrh** [comment]
Hey Steven and Gino,
I can't push my change to app.js; I don't have permission from the project.  How can I get permission, is this something I have to set up?  Let me know!  It's just the document.ready jQuery wrapper, but we should get this out of the way.

**Comment by zorostang** [comment]
I added you as collaborator. You should be able to push now.

**Comment by guillermokrh** [comment]
Hi Steven,
I'm running into issues with MAMP again, could you send me screenshots of your MAMP settings?  Thanks!

**Comment by stevevance** [comment]
@guillermokrh @zorostang Update your Turf.js instance because Mapbox [released 1.4 this week](https://www.mapbox.com/blog/turf-1-4-0-released/).

**Comment by stevevance** [comment]
Fixed, with commit https://github.com/zorostang/chicago_bike_equity/commit/3fc9be4829323688de389f0c28ee95ed53b9864b
